# Generated by Django 3.2 on 2022-11-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kofe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fam', models.CharField(max_length=20)),
                ('yosh', models.IntegerField(default=1)),
                ('ism', models.IntegerField(default=12)),
            ],
        ),
    ]
